### ISSUE TITLE
Kasparovsyncd dag/selected-tip does not seem to contain block relation info

### ISSUE THREAD

**Issue by aspect** [kaspanet/kasparov#39]
When receiving `dag/selected-tip`, notifications, there doesn't seem to be any information meant to relate incoming block to another.

**Comment by ey51** [comment]
Apologies. Block has a new field called parentBlockHashes. It was added 3 days ago. Can you get the latest version, and let me know if it solves it for you?

**Comment by ey51** [comment]
Furthermore, the purpose of dag/selected-tip is for calculating confirmations for transactions and blocks that you know of.
The calculation is `**block**.confirmations` = `dag.selected_tip_block.blue_score` - `**block**.accepting_block.blue_score` + 1.
This allows you to recalculate the confirmations on all blocks that you have, whenever there is a new selected tip block coming in as a notification from `dag/selected-tip`.

**Comment by ey51** [comment]
resolved.
