### ISSUE TITLE
Feature request: support CORS headers and pre-flight checks in Kasparov http server

### ISSUE THREAD

**Issue by aspect** [kaspanet/kasparov#41]
Accessing Kasparovd HTTP API server from non-local host yields CORS policy errors.

I would suggest adding a `--cors` or `--cors-enable` flag to `kasparovd` allowing a user to explicitly enable for cross-origin requests. 

This is an example of CORS-related header handling for NGINX:
https://www.ryadel.com/en/nginx-access-control-allow-origin-cors-policy-settings/

**Comment by ey51** [comment]
It's a bug. It should be enabled by default. It will be handled.

**Comment by someone235** [comment]
Looks like your problem was the fact that you tried to make a CORS request from `file://` origin, which is never possible
